def keywords():
    keywords = [
    "auto",
    "bool",
    "break",
    "case",
    "catch",
    "char",
    "word",
    "class",
    "const",
    "continue",
    "delete",
    "do",
    "double",
    "else",
    "enum",
    "false",
    "float",
    "for",
    "goto",
    "if",
    "#include",
    "int",
    "long",
    "namespace",
    "not",
    "or",
    "private",
    "protected",
    "public",
    "return",
    "short",
    "signed",
    "sizeof",
    "static",
    "struct",
    "switch",
    "true",
    "try",
    "unsigned",
    "void",
    "while",
    ]
    return keywords

def operators():
    operators = {
    "+": "PLUS",
    "-": "MINUS",
    "*": "INMULTIRE",
    "/": "DIV",
    "%": "MOD",
    "+=": "PLUSEGAL",
    "-=": "MINUSEGAL",
    "*=": "INMULTITEGAL",
    "/=": "DIVEGAL",
    "++": "INC",
    "--": "DEC",
    "|": "OR",
    "&&": "AND",
    }
    return operators

def delimiters():
    delimiters = {
    "\t": "TAB",
    "\n": "NEWLINE",
    "(": "PARS",
    ")": "PARD",
    "[": "BRACES",
    "]": "BRACED",
    "{": "ACOLS",
    "}": "ACOLD",
    "=": "ASSIGN",
    ":": "DPCT",
    ",": "VIRG",
    ";": "PCTVIRG",
    "<<": "OUT",
    ">>": "IN",
    }
    return delimiters